
import { useState, useMemo, useRef, useEffect } from 'react';
import Canvas from './components/Canvas';
import ControlPanel from './components/ControlPanel';
import Sidebar from './components/Sidebar';
import { parseFile, API_BASE_URL } from './api';
import type { Point, VoiceControlFile, Command } from './api';

const DEVICES = [
  { id: 'ipad_air_4_landscape', name: 'iPad Air 4 (Landscape)', width: 1180, height: 820 },
  { id: 'iphone_13_portrait', name: 'iPhone 13 (Portrait)', width: 390, height: 844 },
  { id: 'iphone_13_landscape', name: 'iPhone 13 (Landscape)', width: 844, height: 390 },
];

// Template for new command (generated by backend/generate_template.py)
const TEMPLATE_PLIST_BASE64 = "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIHBsaXN0IFBVQkxJQyAiLS8vQXBwbGUvL0RURCBQTElTVCAxLjAvL0VOIiAiaHR0cDovL3d3dy5hcHBsZS5jb20vRFREcy9Qcm9wZXJ0eUxpc3QtMS4wLmR0ZCI+CjxwbGlzdCB2ZXJzaW9uPSIxLjAiPgo8ZGljdD4KCTxrZXk+Q29tbWFuZHNUYWJsZTwva2V5PgoJPGRpY3Q+CgkJPGtleT5DdXN0b20uMTc2NDkyNzUxNi5lYzVjODE8L2tleT4KCQk8ZGljdD4KCQkJPGtleT5Db21tYW5kSUQ8L2tleT4KCQkJPHN0cmluZz5DdXN0b20uMTc2NDkyNzUxNi5lYzVjODE8L3N0cmluZz4KCQkJPGtleT5DdXN0b21Db21tYW5kczwva2V5PgoJCQk8ZGljdD4KCQkJCTxrZXk+ZW5fVVM8L2tleT4KCQkJCTxhcnJheT4KCQkJCQk8c3RyaW5nPk5ldyBDb21tYW5kPC9zdHJpbmc+CgkJCQk8L2FycmF5PgoJCQkJPGtleT5qYV9KUDwva2V5PgoJCQkJPGFycmF5PgoJCQkJCTxzdHJpbmc+5paw6KaP44Kz44Oe44Oz44OJPC9zdHJpbmc+CgkJCQk8L2FycmF5PgoJCQk8L2RpY3Q+CgkJCTxrZXk+Q3VzdG9tR2VzdHVyZTwva2V5PgoJCQk8ZGF0YT4KCQkJWW5Cc2FYTjBNRERVQVFJREJBVUdGeHBaSkdGeVkyaHBkbVZ5V0NSdlltcGxZM1J6VkNSMAoJCQliM0JZSkhabGNuTnBiMjVmRUE5T1UwdGxlV1ZrUVhKamFHbDJaWEtsQndnUEVCRlZKRzUxCgkJCWJHelNDUW9MREZZa1kyeGhjM05hVGxNdWIySnFaV04wYzRBRW9nME9nQUtBQTFwN05UQXcKCQkJTENBME1EQjlXbnMyTURBc0lEUXdNSDNTRWhNVUZWZ2tZMnhoYzNObGMxb2tZMnhoYzNOdQoJCQlZVzFsb2hVV1YwNVRRWEp5WVhsWVRsTlBZbXBsWTNUUkdCbFVjbTl2ZElBQkVnQUJocUFJCgkJCUVSc2tLVEpFU2xCVlhHZHBiRzV3ZTRhTGxKK2lxck8ydTcwQUFBQUFBQUFCQVFBQUFBQUEKCQkJQUFBYkFBQUFBQUFBQUFBQUFBQUFBQUFBd2c9PQoJCQk8L2RhdGE+CgkJCTxrZXk+RW5hYmxlZDwva2V5PgoJCQk8dHJ1ZS8+CgkJPC9kaWN0PgoJPC9kaWN0PgoJPGtleT5FeHBvcnREYXRlPC9rZXk+Cgk8cmVhbD4xNzY0OTI3NTE2LjAyNzg1NTk8L3JlYWw+Cgk8a2V5PlZlcnNpb248L2tleT4KCTxyZWFsPjEuMDwvcmVhbD4KPC9kaWN0Pgo8L3BsaXN0Pgo=";

const DEFAULT_COMMAND_POINTS: Point[] = [
  { x: 160, y: 400 }, // Start point
  { x: 160, y: 300 }  // End point (Swipe Up)
];

const FILE_COLORS = [
  '#3B82F6', // Blue
  '#F59E0B', // Yellow
  '#8B5CF6', // Purple
  '#EC4899', // Pink
  '#6366F1', // Indigo
  '#14B8A6', // Teal
  '#06B6D4', // Cyan
  '#F97316', // Orange
];

function App() {
  const [files, setFiles] = useState<VoiceControlFile[]>([]);
  // Helper to get next color
  const getNextColor = (currentFiles: VoiceControlFile[]) => {
    const usedColors = new Set(currentFiles.map(f => f.color));
    for (const color of FILE_COLORS) {
      if (!usedColors.has(color)) return color;
    }
    return FILE_COLORS[currentFiles.length % FILE_COLORS.length];
  };

  const [selectedFileId, setSelectedFileId] = useState<string | null>(null);
  const [selectedDeviceId, setSelectedDeviceId] = useState<string>(DEVICES[0].id);
  const [backgroundImage, setBackgroundImage] = useState<string | null>(null);
  const [showGrid, setShowGrid] = useState<boolean>(true);
  const [isSidebarOpen, setIsSidebarOpen] = useState<boolean>(true);
  const [isFullscreen, setIsFullscreen] = useState<boolean>(false);
  const [showSettingsPopup, setShowSettingsPopup] = useState<boolean>(false);
  const [duration, setDuration] = useState<number>(1.0); // Default 1.0s
  const [isPlaying, setIsPlaying] = useState<boolean>(false);
  const [simulationProgress, setSimulationProgress] = useState<number | null>(null);

  const appRef = useRef<HTMLDivElement>(null);
  const animationRef = useRef<number | null>(null);
  const startTimeRef = useRef<number | null>(null);

  useEffect(() => {
    const handleFullscreenChange = () => {
      setIsFullscreen(!!document.fullscreenElement);
      if (!document.fullscreenElement) {
        setShowSettingsPopup(false);
      }
    };

    document.addEventListener('fullscreenchange', handleFullscreenChange);
    return () => document.removeEventListener('fullscreenchange', handleFullscreenChange);
  }, []);

  // Animation Loop
  useEffect(() => {
    if (isPlaying) {
      const animate = (time: number) => {
        if (startTimeRef.current === null) {
          startTimeRef.current = time;
        }

        const elapsed = (time - startTimeRef.current) / 1000; // seconds
        const progress = Math.min(elapsed / duration, 1.0);

        setSimulationProgress(progress);

        if (progress < 1.0) {
          animationRef.current = requestAnimationFrame(animate);
        } else {
          setIsPlaying(false);
          setSimulationProgress(null);
          startTimeRef.current = null;
        }
      };

      animationRef.current = requestAnimationFrame(animate);
    } else {
      if (animationRef.current) {
        cancelAnimationFrame(animationRef.current);
      }
      setSimulationProgress(null);
      startTimeRef.current = null;
    }

    return () => {
      if (animationRef.current) {
        cancelAnimationFrame(animationRef.current);
      }
    };
  }, [isPlaying, duration]);

  const togglePlay = () => {
    setIsPlaying(!isPlaying);
  };

  useEffect(() => {
    const handleFullscreenChange = () => {
      const isFull = !!document.fullscreenElement;
      console.log('Fullscreen change:', isFull);
      setIsFullscreen(isFull);
    };

    document.addEventListener('fullscreenchange', handleFullscreenChange);
    return () => {
      document.removeEventListener('fullscreenchange', handleFullscreenChange);
    };
  }, []);

  const selectedDevice = useMemo(() => {
    return DEVICES.find(d => d.id === selectedDeviceId) || DEVICES[0];
  }, [selectedDeviceId]);

  // ... (rest of the code)


  const handleCreateNewFile = async () => {
    try {
      // Convert base64 template to Blob/File to reuse parseFile logic (or just mock it)
      // Since parseFile takes a File object and sends it to backend, we can create a File from base64.

      const byteCharacters = atob(TEMPLATE_PLIST_BASE64);
      const byteNumbers = new Array(byteCharacters.length);
      for (let i = 0; i < byteCharacters.length; i++) {
        byteNumbers[i] = byteCharacters.charCodeAt(i);
      }
      const byteArray = new Uint8Array(byteNumbers);
      const blob = new Blob([byteArray], { type: 'application/x-plist' });
      const file = new File([blob], "New File.voicecontrolcommands", { type: 'application/x-plist' });

      const result = await parseFile(file);

      const newCommands = result.commands.map(c => {
        const newId = crypto.randomUUID();
        // Generate points for default duration (0.4s)
        const initialPoints = resamplePath(DEFAULT_COMMAND_POINTS, 0.4);
        return {
          ...c,
          id: newId,
          points: initialPoints,
          isVisible: true,
          duration: 0.4
        };
      });

      const newFile: VoiceControlFile = {
        id: crypto.randomUUID(),
        name: "New File",
        originalContent: TEMPLATE_PLIST_BASE64,
        commands: newCommands,
        offsetX: 0,
        offsetY: 0,
        selectedCommandId: newCommands.length > 0 ? newCommands[0].id : null,
        isVisible: true,
        color: getNextColor(files),
      };

      setFiles(prev => [...prev, newFile]);
      setSelectedFileId(newFile.id);
      setDuration(0.4); // Sync global duration

    } catch (error) {
      console.error('Error creating new file:', error);
      alert('Failed to create new file.');
    }
  };

  const handleBackgroundImageUpload = (file: File) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      const result = e.target?.result as string;
      setBackgroundImage(result);

      // Auto-detect device based on image aspect ratio/dimensions
      const img = new Image();
      img.onload = () => {
        const width = img.width;
        const height = img.height;
        const aspectRatio = width / height;

        // Find best matching device
        // We check if the aspect ratio matches closely (within small tolerance)
        // or if dimensions match exactly (scaled)
        const matchedDevice = DEVICES.find(device => {
          const deviceRatio = device.width / device.height;
          return Math.abs(aspectRatio - deviceRatio) < 0.01;
        });

        if (matchedDevice) {
          setSelectedDeviceId(matchedDevice.id);
          console.log(`Auto-detected device: ${matchedDevice.name}`);
        }
      };
      img.src = result;
    };
    reader.readAsDataURL(file);
  };

  const handleClearBackgroundImage = () => {
    setBackgroundImage(null);
  };

  const handleDeleteFile = (id: string) => {
    setFiles(prev => prev.filter(f => f.id !== id));
    if (selectedFileId === id) {
      setSelectedFileId(null);
    }
  };

  const handleDeleteCommand = (fileId: string, commandId: string) => {
    setFiles(prev => prev.map(f => {
      if (f.id !== fileId) return f;
      const newCommands = f.commands.filter(c => c.id !== commandId);
      return {
        ...f,
        commands: newCommands,
        selectedCommandId: f.selectedCommandId === commandId ? (newCommands.length > 0 ? newCommands[0].id : null) : f.selectedCommandId
      };
    }));
  };

  const handleToggleVisibility = (id: string) => {
    setFiles(prev => prev.map(f => f.id === id ? { ...f, isVisible: !f.isVisible } : f));
  };

  const handleToggleCommandVisibility = (fileId: string, commandId: string) => {
    setFiles(prev => prev.map(f => {
      if (f.id !== fileId) return f;
      return {
        ...f,
        commands: f.commands.map(c => c.id === commandId ? { ...c, isVisible: !c.isVisible } : c)
      };
    }));
  };

  const handleToggleAllVisibility = () => {
    setFiles(prev => {
      const allVisible = prev.every(f => f.isVisible && f.commands.every(c => c.isVisible !== false));
      const newState = !allVisible;
      return prev.map(f => ({
        ...f,
        isVisible: newState,
        commands: f.commands.map(c => ({ ...c, isVisible: newState }))
      }));
    });
  };

  const handleRenameFile = (fileId: string, newName: string) => {
    setFiles(prev => prev.map(f => f.id === fileId ? { ...f, name: newName } : f));
  };

  const handleRenameCommand = (fileId: string, commandId: string, newName: string) => {
    setFiles(prev => prev.map(f => {
      if (f.id !== fileId) return f;
      return {
        ...f,
        commands: f.commands.map(c => c.id === commandId ? { ...c, name: newName } : c)
      };
    }));
  };

  const selectedFile = useMemo(() => {
    return files.find(f => f.id === selectedFileId);
  }, [files, selectedFileId]);

  const updateSelectedFile = (updates: Partial<VoiceControlFile>) => {
    if (!selectedFileId) return;
    setFiles(prev => prev.map(f => f.id === selectedFileId ? { ...f, ...updates } : f));
  };

  const selectedCommand = useMemo(() => {
    if (!selectedFile || !selectedFile.selectedCommandId) return undefined;
    return selectedFile.commands.find(c => c.id === selectedFile.selectedCommandId);
  }, [selectedFile]);

  // Update duration when selected file/command changes
  useEffect(() => {
    if (selectedCommand) {
      // Estimate duration from points (assuming 60fps)
      const estimatedDuration = selectedCommand.points.length / 60;
      // Round to 1 decimal place
      setDuration(Math.round(estimatedDuration * 10) / 10);
    }
  }, [selectedCommand]);

  // Compute paths for all visible files
  const canvasPaths = useMemo(() => {
    return files
      .filter(f => f.isVisible)
      .flatMap(f =>
        f.commands
          .filter(c => c.isVisible !== false)
          .map((cmd, index) => {
            const isSelected = cmd.id === selectedFile?.selectedCommandId;
            return {
              id: cmd.id,
              fileId: f.id,
              commandId: cmd.id,
              points: cmd.points.map(p => ({
                x: p.x + f.offsetX,
                y: p.y + f.offsetY
              })),
              color: f.color,
              isSelected: isSelected,
              label: (f.id === selectedFileId) ? String(index + 1) : undefined
            };
          })
      );
  }, [files, selectedFileId, selectedFile]);
  // Points for export (only for the selected file)
  const exportPoints = useMemo<Point[]>(() => {
    if (!selectedCommand || !selectedFile) return [];
    return selectedCommand.points.map(p => ({
      x: p.x + selectedFile.offsetX,
      y: p.y + selectedFile.offsetY,
    }));
  }, [selectedCommand, selectedFile]);

  const resamplePath = (points: Point[], dur: number): Point[] => {
    if (points.length === 0) return [];

    const targetCount = Math.max(2, Math.round(dur * 60)); // 60Hz

    // If it's a single point (Tap), just repeat it
    if (points.length === 1) {
      return Array(targetCount).fill(points[0]);
    }

    // If it's a straight line (2 points), use linear interpolation
    if (points.length === 2) {
      const start = points[0];
      const end = points[1];
      const newPoints: Point[] = [];
      for (let i = 0; i < targetCount; i++) {
        const t = i / (targetCount - 1);
        newPoints.push({
          x: start.x + (end.x - start.x) * t,
          y: start.y + (end.y - start.y) * t,
        });
      }
      return newPoints;
    }

    // For complex paths, we need to resample along the path length
    // 1. Calculate total length and segment lengths
    let totalLength = 0;
    const segmentLengths: number[] = [];
    for (let i = 0; i < points.length - 1; i++) {
      const dx = points[i + 1].x - points[i].x;
      const dy = points[i + 1].y - points[i].y;
      const dist = Math.sqrt(dx * dx + dy * dy);
      segmentLengths.push(dist);
      totalLength += dist;
    }

    if (totalLength === 0) {
      return Array(targetCount).fill(points[0]);
    }

    const newPoints: Point[] = [points[0]]; // Start with first point
    const step = totalLength / (targetCount - 1);

    let currentDist = 0;
    let currentSegmentIndex = 0;

    for (let i = 1; i < targetCount - 1; i++) {
      const targetDist = i * step;

      // Find the segment that contains targetDist
      while (currentSegmentIndex < segmentLengths.length && currentDist + segmentLengths[currentSegmentIndex] < targetDist) {
        currentDist += segmentLengths[currentSegmentIndex];
        currentSegmentIndex++;
      }

      if (currentSegmentIndex >= segmentLengths.length) {
        newPoints.push(points[points.length - 1]);
        continue;
      }

      const segmentStart = points[currentSegmentIndex];
      const segmentEnd = points[currentSegmentIndex + 1];
      const segmentLen = segmentLengths[currentSegmentIndex];

      const distInSegment = targetDist - currentDist;
      const t = distInSegment / segmentLen;

      newPoints.push({
        x: segmentStart.x + (segmentEnd.x - segmentStart.x) * t,
        y: segmentStart.y + (segmentEnd.y - segmentStart.y) * t
      });
    }

    newPoints.push(points[points.length - 1]); // End with last point
    return newPoints;
  };



  // Calculate Angle and Length
  const { angle, length } = useMemo(() => {
    if (!selectedCommand || selectedCommand.points.length < 2) return { angle: 0, length: 0 };

    const start = selectedCommand.points[0];
    const end = selectedCommand.points[selectedCommand.points.length - 1];

    const dx = end.x - start.x;
    const dy = end.y - start.y; // Y increases downwards in canvas usually, but let's check coordinate system.
    // In standard math, y increases upwards. In canvas, y increases downwards.
    // angle = atan2(dy, dx).
    // We want 0-1023 mapping.
    // 0 = Right (0 rad), 256 = Down (PI/2), 512 = Left (PI), 768 = Up (-PI/2 or 3PI/2)

    let rad = Math.atan2(dy, dx);
    if (rad < 0) rad += 2 * Math.PI;

    const angleVal = (rad / (2 * Math.PI)) * 1024;
    const lengthVal = Math.sqrt(dx * dx + dy * dy);

    return { angle: angleVal, length: lengthVal };
  }, [selectedCommand]);

  const handleAngleChange = (newAngle: number) => {
    if (!selectedFileId || !selectedCommand || selectedCommand.points.length < 2) return;

    const start = selectedCommand.points[0];
    const end = selectedCommand.points[selectedCommand.points.length - 1];

    const midX = (start.x + end.x) / 2;
    const midY = (start.y + end.y) / 2;

    const rad = (newAngle / 1024) * 2 * Math.PI;
    const halfLen = length / 2;

    const dx = Math.cos(rad) * halfLen;
    const dy = Math.sin(rad) * halfLen;

    const newStart = { x: midX - dx, y: midY - dy };
    const newEnd = { x: midX + dx, y: midY + dy };
    // Update points (straight line)
    // We need to keep the duration (point count) consistent or update it?
    // If we drag start/end, we probably want to keep the duration (speed) roughly same?
    // Or keep point count same?
    // generateStraightLinePoints used duration to calculate count.
    // Let's use resamplePath with current duration.
    // But we need to know duration.
    // If cmd.duration is set, use it. Else default 1.0.
    const command = selectedCommand; // Assuming selectedCommand is the command being modified
    const duration = command.duration || 1.0;
    const newPoints = resamplePath([newStart, newEnd], duration);

    updateSelectedFile({
      commands: selectedFile!.commands.map(c =>
        c.id === command.id ? { ...c, points: newPoints } : c
      )
    });
  };

  const handleLengthChange = (newLength: number) => {
    if (!selectedFileId || !selectedCommand || selectedCommand.points.length < 2) return;

    const start = selectedCommand.points[0];
    const end = selectedCommand.points[selectedCommand.points.length - 1];

    const midX = (start.x + end.x) / 2;
    const midY = (start.y + end.y) / 2;

    // Keep current angle
    const dx = end.x - start.x;
    const dy = end.y - start.y;
    const rad = Math.atan2(dy, dx);

    const halfLen = newLength / 2;
    const newDx = Math.cos(rad) * halfLen;
    const newDy = Math.sin(rad) * halfLen;

    const newStart = { x: midX - newDx, y: midY - newDy };
    const newEnd = { x: midX + newDx, y: midY + newDy };

    const command = selectedCommand;
    const duration = command.duration || 1.0;
    const newPoints = resamplePath([newStart, newEnd], duration);

    updateSelectedFile({
      commands: selectedFile!.commands.map(c =>
        c.id === selectedCommand.id ? { ...c, points: newPoints } : c
      )
    });
  };


  const handlePathDrag = (id: string, deltaX: number, deltaY: number, type: 'move' | 'start' | 'end') => {
    if (isPlaying) return;

    setFiles(prev => prev.map(f => {
      // Find if this file contains the command
      const cmdIndex = f.commands.findIndex(c => c.id === id);
      if (cmdIndex === -1) return f;

      const cmd = f.commands[cmdIndex];
      let newPoints = [...cmd.points];

      if (type === 'move') {
        newPoints = newPoints.map(p => ({ x: p.x + deltaX, y: p.y + deltaY }));
      } else if (type === 'start') {
        const newStart = { x: newPoints[0].x + deltaX, y: newPoints[0].y + deltaY };
        const end = newPoints[newPoints.length - 1];
        // Regenerate points to keep it a straight line
        newPoints = resamplePath([newStart, end], duration);
      } else if (type === 'end') {
        const start = newPoints[0];
        const newEnd = { x: newPoints[newPoints.length - 1].x + deltaX, y: newPoints[newPoints.length - 1].y + deltaY };
        // Regenerate points to keep it a straight line
        newPoints = resamplePath([start, newEnd], duration);
      }

      const newCommands = [...f.commands];
      newCommands[cmdIndex] = { ...cmd, points: newPoints };

      return { ...f, commands: newCommands };
    }));
  };

  const handleFileUpload = async (file: File) => {
    try {
      const reader = new FileReader();
      reader.onload = async (e) => {
        const content = e.target?.result as string;
        const base64Content = content.split(',')[1];

        const result = await parseFile(file);

        // Strip extension for display name
        const nameWithoutExt = file.name.replace(/\.(voicecontrolcommands|plist)$/i, '');

        const newFile: VoiceControlFile = {
          id: crypto.randomUUID(),
          name: nameWithoutExt,
          originalContent: base64Content,
          commands: result.commands.map(c => {
            const newId = crypto.randomUUID();
            return {
              ...c,
              id: newId, // Regenerate ID to ensure uniqueness across files
              points: c.points.map(p => ({ ...p })), // Deep copy points
              isVisible: true
            };
          }),
          offsetX: 0,
          offsetY: 0,
          selectedCommandId: null, // Will be set after commands are processed
          isVisible: true,
          color: getNextColor(files),
        };

        // Set selected command to the first one (with the new ID)
        if (newFile.commands.length > 0) {
          newFile.selectedCommandId = newFile.commands[0].id;
        }

        setFiles(prev => [...prev, newFile]);
        setSelectedFileId(newFile.id);
      };
      reader.readAsDataURL(file);
    } catch (error) {
      console.error('Error parsing file:', error);
      alert(`Failed to parse file: ${file.name}`);
    }
  };

  const handleExport = async () => {
    if (!selectedFile || !selectedFile.selectedCommandId || !selectedCommand) return;

    // Ensure filename has .plist extension
    // Use command name for single command export
    let filename = selectedCommand.name;
    if (!filename.toLowerCase().endsWith('.plist')) {
      filename += '.plist';
    }

    const commandsToExport = [{
      name: selectedCommand.name,
      points: exportPoints
    }];

    // @ts-ignore
    if (typeof window.showSaveFilePicker === 'function') {
      try {
        // 1. Get File Handle IMMEDIATELY (User Activation)
        // @ts-ignore
        const handle = await window.showSaveFilePicker({
          suggestedName: filename,
          types: [{
            description: 'Voice Control Commands',
            accept: { 'application/x-plist': ['.plist'] },
          }],
        });

        // 2. Perform API Call
        const response = await fetch(`${API_BASE_URL}/export_merged`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ commands: commandsToExport }),
        });

        if (!response.ok) {
          throw new Error('Export failed');
        }

        const result = await response.json();

        // 3. Write to File
        const writable = await handle.createWritable();
        const binaryContent = Uint8Array.from(atob(result.content), c => c.charCodeAt(0));
        await writable.write(binaryContent);
        await writable.close();

        alert('ファイルが正常に保存されました！');
      } catch (err: any) {
        if (err.name === 'AbortError') {
          return; // User cancelled
        }
        console.error('File Save Error:', err);
        alert(`ファイルシステムアクセスAPIエラー: ${err.message}`);
      }
    } else {
      // Fallback for browsers not supporting File System Access API
      try {
        const response = await fetch(`${API_BASE_URL}/export_merged`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ commands: commandsToExport }),
        });

        if (!response.ok) {
          throw new Error('Export failed');
        }

        const result = await response.json();

        const blob = new Blob([Uint8Array.from(atob(result.content), c => c.charCodeAt(0))], { type: 'application/x-plist' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
      } catch (err: any) {
        console.error('Export Error:', err);
        alert(`エクスポートエラー: ${err.message}`);
      }
    }
  };

  const handleEnterFullscreen = () => {
    if (appRef.current) {
      appRef.current.requestFullscreen().catch((err: any) => {
        console.error(`Error attempting to enable full - screen mode: ${err.message}(${err.name})`);
      });
    }
  };

  const handleExitFullscreen = () => {
    if (document.fullscreenElement) {
      document.exitFullscreen().catch((err: any) => {
        console.error(`Error attempting to exit full - screen mode: ${err.message}(${err.name})`);
      });
    }
  };

  const handleExportVisible = async () => {
    const visibleFiles = files.filter(f => f.isVisible);
    if (visibleFiles.length === 0) {
      alert('表示されているファイルがありません。');
      return;
    }

    const commandsToExport = visibleFiles.map(f => {
      return f.commands.filter(c => c.isVisible !== false).map(cmd => ({
        name: cmd.name,
        points: cmd.points.map(p => ({
          x: p.x + f.offsetX,
          y: p.y + f.offsetY
        }))
      }));
    }).flat();

    try {
      const response = await fetch('http://localhost:8000/api/export_merged', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ commands: commandsToExport }),
      });

      if (!response.ok) {
        throw new Error('Export failed');
      }

      const result = await response.json();

      // Save logic (reuse from handleExport)
      // @ts-ignore
      if (typeof window.showSaveFilePicker === 'function') {
        // @ts-ignore
        const handle = await window.showSaveFilePicker({
          suggestedName: 'merged.voicecontrolcommands',
          types: [{
            description: 'Voice Control Commands',
            accept: { 'application/x-plist': ['.plist'] },
          }],
        });
        const writable = await handle.createWritable();
        const binaryContent = Uint8Array.from(atob(result.content), c => c.charCodeAt(0));
        await writable.write(binaryContent);
        await writable.close();
        alert('ファイルが正常に保存されました！');
      } else {
        alert('このブラウザはファイルシステムアクセスAPIをサポートしていません。');
      }

    } catch (error: any) {
      console.error('Export Error:', error);
      alert(`エクスポートエラー: ${error.message}`);
    }
  };

  const handleAddCommandToFile = (fileId: string) => {
    setFiles(prev => prev.map(f => {
      if (f.id !== fileId) return f;

      // Generate points for default duration (0.4s)
      const initialPoints = resamplePath(DEFAULT_COMMAND_POINTS, 0.4);

      const newCommand: Command = {
        id: crypto.randomUUID(),
        name: `New Command ${f.commands.length + 1}`,
        points: initialPoints,
        isVisible: true,
        duration: 0.4
      };
      return {
        ...f,
        commands: [...f.commands, newCommand],
        selectedCommandId: newCommand.id // Auto-select new command
      };
    }));
    setSelectedFileId(fileId); // Ensure file is selected
    setDuration(0.4); // Sync global duration
  };

  const handleAddTapCommand = (fileId: string) => {
    setFiles(prev => prev.map(f => {
      if (f.id !== fileId) return f;
      const defaultDuration = 0.1;
      const defaultPoint = { x: 160, y: 300 };
      // Generate points for 0.1s (6 points at 60Hz)
      const initialPoints = resamplePath([defaultPoint], defaultDuration);

      const newCommand: Command = {
        id: crypto.randomUUID(),
        name: "New Tap",
        points: initialPoints,
        isVisible: true,
        duration: defaultDuration
      };

      return {
        ...f,
        commands: [...f.commands, newCommand],
        selectedCommandId: newCommand.id // Auto-select new command
      };
    }));
    setSelectedFileId(fileId); // Ensure file is selected
  };

  const handleExportFile = async (fileId: string) => {
    const file = files.find(f => f.id === fileId);
    if (!file) return;

    // Use export_merged logic to ensure all commands (including new ones) are included
    // @ts-ignore
    if (typeof window.showSaveFilePicker === 'function') {
      try {
        // @ts-ignore
        const handle = await window.showSaveFilePicker({
          suggestedName: file.name.endsWith('.plist') ? file.name : `${file.name}.plist`,
          types: [{
            description: 'Voice Control Commands',
            accept: { 'application/x-plist': ['.plist'] },
          }],
        });

        const commandsToExport = file.commands.map(c => ({
          name: c.name,
          points: c.points.map(p => ({
            x: p.x + file.offsetX,
            y: p.y + file.offsetY
          })),
          duration: c.duration
        }));

        const response = await fetch(`${API_BASE_URL}/export_merged`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ commands: commandsToExport }),
        });

        if (!response.ok) {
          throw new Error('Export failed');
        }

        const result = await response.json();
        const writable = await handle.createWritable();
        const binaryContent = Uint8Array.from(atob(result.content), c => c.charCodeAt(0));
        await writable.write(binaryContent);
        await writable.close();

        alert('ファイルが正常に保存されました！');
      } catch (err: any) {
        if (err.name === 'AbortError') return;
        console.error('Export Error:', err);
        alert(`エクスポートエラー: ${err.message}`);
      }
    } else {
      alert('このブラウザはファイルシステムアクセスAPIをサポートしていません。');
    }
  };

  const handleSelectCommand = (fileId: string, commandId: string) => {
    setSelectedFileId(fileId);
    setFiles(prev => prev.map(f => {
      if (f.id === fileId) {
        const cmd = f.commands.find(c => c.id === commandId);
        if (cmd && cmd.duration !== undefined) {
          setDuration(cmd.duration);
        } else {
          // Default duration if not set (e.g. for paths, maybe keep 1.0 or calculate?)
          // Also update global duration state to match new command
          setDuration(0.4);
        }
        return { ...f, selectedCommandId: commandId };
      }
      return f;
    }));
  };

  return (
    <div ref={appRef} className="flex h-screen bg-gray-100 overflow-hidden">
      {isFullscreen && (
        <button
          onClick={handleExitFullscreen}
          className="fixed top-4 right-4 z-[9999] p-2 bg-white/80 hover:bg-white rounded-full shadow-lg transition-colors duration-200"
          title="Exit Fullscreen"
        >
          <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-gray-700" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
        </button>
      )}

      {!isFullscreen && isSidebarOpen && (
        <Sidebar
          files={files}
          selectedFileId={selectedFileId}
          onSelectFile={setSelectedFileId}
          onSelectCommand={handleSelectCommand}
          onDeleteFile={handleDeleteFile}
          onToggleVisibility={handleToggleVisibility}
          onFileUpload={handleFileUpload}
          onCreateNew={handleCreateNewFile}
          onExportVisible={handleExportVisible}
          onToggleCommandVisibility={handleToggleCommandVisibility}
          onToggleAllVisibility={handleToggleAllVisibility}
          onRenameFile={handleRenameFile}
          onRenameCommand={handleRenameCommand}
          onDeleteCommand={handleDeleteCommand}
          onAddCommandToFile={handleAddCommandToFile}
          onAddTapCommand={handleAddTapCommand}
          onExportFile={handleExportFile}
        />
      )}

      <div className="flex-1 flex flex-col overflow-hidden relative">
        {!isFullscreen && (
          <header className="bg-white shadow-sm p-4 z-10 flex items-center">
            <button
              onClick={() => setIsSidebarOpen(!isSidebarOpen)}
              className="mr-4 text-gray-600 hover:text-gray-900 focus:outline-none"
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
              </svg>
            </button>
            <h1 className="text-2xl font-bold text-gray-900">Voice Control Commander</h1>
          </header>
        )}

        <main className={`flex-1 overflow-auto ${isFullscreen ? 'p-0 flex items-center justify-center bg-gray-900' : 'p-8'}`}>
          {selectedFile ? (
            <div className={`${isFullscreen ? 'w-full h-full flex items-center justify-center' : 'grid grid-cols-1 lg:grid-cols-3 gap-8'}`}>
              <div className={`${isFullscreen ? 'w-full h-full flex items-center justify-center' : 'lg:col-span-2'}`}>
                <Canvas
                  paths={canvasPaths}
                  width={selectedDevice.width}
                  height={selectedDevice.height}
                  backgroundImage={backgroundImage}
                  showGrid={showGrid}
                  style={isFullscreen ? { maxHeight: '95vh' } : undefined}
                  onPathDrag={handlePathDrag}
                  onSelectCommand={handleSelectCommand}
                  simulationProgress={simulationProgress}
                />
                {!isFullscreen && (
                  <div className="mt-4 text-sm text-gray-500">
                    ファイル: {selectedFile.name} | コマンド: {selectedCommand?.name || 'なし'} | デバイス: {selectedDevice.name} ({selectedDevice.width}x{selectedDevice.height})
                  </div>
                )}
              </div>

              {(!isFullscreen || showSettingsPopup) && (
                <div className={`${isFullscreen ? 'absolute top-16 right-4 w-96 z-50 max-h-[80vh] overflow-y-auto' : ''}`}>
                  <ControlPanel
                    offsetX={selectedFile.offsetX}
                    offsetY={selectedFile.offsetY}
                    onOffsetXChange={(val) => updateSelectedFile({ offsetX: val })}
                    onOffsetYChange={(val) => updateSelectedFile({ offsetY: val })}
                    onExport={handleExport}
                    devices={DEVICES}
                    selectedDeviceId={selectedDeviceId}
                    onSelectDevice={setSelectedDeviceId}
                    onBackgroundImageUpload={handleBackgroundImageUpload}
                    onClearBackgroundImage={handleClearBackgroundImage}
                    showGrid={showGrid}
                    onToggleGrid={setShowGrid}
                    onEnterFullscreen={handleEnterFullscreen}
                    duration={duration}
                    onDurationChange={(newDuration) => {
                      setDuration(newDuration);
                      if (selectedFileId && selectedFile?.selectedCommandId) {
                        setFiles(prev => prev.map(f => {
                          if (f.id === selectedFileId) {
                            return {
                              ...f,
                              commands: f.commands.map(c => {
                                if (c.id === f.selectedCommandId) {
                                  // Resample points based on new duration
                                  // But wait, if we resample, we lose the original "key" points if we are not careful.
                                  // However, for Voice Control, the points ARE the definition.
                                  // So resampling is the correct way to change speed.
                                  // But we should be careful not to degrade quality too much if user toggles back and forth.
                                  // Ideally we store "original path" but that's complex.
                                  // For now, resampling the *current* points is the standard way.

                                  // Special case: If it's a Tap (1 point originally), we want to keep it as "Tap" conceptually?
                                  // If we resample a 1-point tap to 6 points, it becomes a "hold".
                                  // But the user wants to regulate time.
                                  // If we resample, it becomes multiple points.
                                  // Does our Canvas handle multiple points at same location as a Tap?
                                  // Our Canvas checks `points.length === 1`.
                                  // If we have 6 points at same location, Canvas will draw it as a line (dot).
                                  // We might need to update Canvas to treat "all points same" as Tap.
                                  // OR, we keep `points` as 1 point in the state, but expand it during export?
                                  // But the user said "time cannot be regulated".
                                  // If we want the simulation to work, we need points?
                                  // Actually simulation uses `duration` state.
                                  // So for simulation, we don't need to resample.
                                  // But for EXPORT, we need to resample.

                                  // User said "drag and tap".
                                  // If I resample drag, it works.
                                  // If I resample tap, it becomes multiple points.
                                  // If I change tap to multiple points, Canvas might draw it as a very short line or dot.
                                  // Let's try to keep it simple: Update duration metadata AND resample points.
                                  // But if we resample tap to 6 points, Canvas will see length=6 and draw a line.
                                  // We should update Canvas to handle this case or just accept it.
                                  // Actually, if points are identical, `ctx.lineTo` does nothing visible.
                                  // But `isPointOnPath` might be weird.

                                  // Let's use `resamplePath`.
                                  const newPoints = resamplePath(c.points, newDuration);
                                  return { ...c, points: newPoints, duration: newDuration };
                                }
                                return c;
                              })
                            };
                          }
                          return f;
                        }));
                      }
                    }}
                    isPlaying={isPlaying}
                    onTogglePlay={togglePlay}
                    angle={angle}
                    onAngleChange={handleAngleChange}
                    length={length}
                    onLengthChange={handleLengthChange}
                  />
                </div>
              )}

              {isFullscreen && (
                <button
                  onClick={() => setShowSettingsPopup(!showSettingsPopup)}
                  className="fixed top-4 right-16 bg-white/80 hover:bg-white p-2 rounded-full shadow-lg z-50 transition duration-200"
                  title="Settings"
                >
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-gray-800" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                  </svg>
                </button>
              )}
            </div>
          ) : (
            <div className="flex items-center justify-center h-full text-gray-400">
              <div className="text-center">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-16 w-16 mx-auto mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M9 13h6m-3-3v6m5 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                <p className="text-xl mb-6">ファイルを選択またはアップロードして開始してください</p>

                <div className="flex justify-center space-x-4">
                  <label className="flex items-center px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 cursor-pointer transition duration-200">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12" />
                    </svg>
                    ファイルを読み込む
                    <input type="file" className="hidden" accept=".voicecontrolcommands,.plist" onChange={(e) => {
                      if (e.target.files && e.target.files.length > 0) {
                        handleFileUpload(e.target.files[0]);
                        e.target.value = '';
                      }
                    }} />
                  </label>

                  <button
                    onClick={handleCreateNewFile}
                    className="flex items-center px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 transition duration-200"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                    </svg>
                    新規ファイル
                  </button>
                </div>
              </div>
            </div>
          )}
        </main>
      </div>
    </div>
  );
}

export default App;

